export const operationalDailyUatPlan = {
  title: "UAT Skenario Operasional Harian",
  version: "Part 7A",
  mode: "Checklist Read-Only",
  warning:
    "Jalankan di Owner/Tangerang. Jangan klik simpan live untuk transaksi sungguhan kecuali memang sedang UAT dengan data yang disetujui owner.",
  phases: [
    {
      id: "PRE",
      title: "Persiapan Sebelum UAT",
      goal: "Pastikan sistem aman, backup siap, dan baseline saldo/stok dicatat.",
      steps: [
        "Login sebagai Owner/Tangerang.",
        "Buka Data Health dan pastikan Masalah Bahaya = 0.",
        "Buka Go-Live Check dan pastikan tidak ada blocker.",
        "Buka Print & Backup lalu export/copy ringkasan sebelum mulai.",
        "Catat stok awal ayam, stok jadi, saldo dompet, hutang Nana, dan piutang.",
        "Tentukan tanggal UAT dan customer/supplier UAT yang akan dipakai.",
      ],
      passCriteria: [
        "Data Health tidak punya Masalah Bahaya.",
        "Owner session aktif.",
        "Baseline saldo/stok tercatat.",
      ],
    },
    {
      id: "UAT-01",
      title: "DROP Ayam → Lot Ayam → Hutang Nana",
      goal: "Menguji satu nota ayam masuk menjadi lot harga aktual dan hutang supplier.",
      steps: [
        "Buka DROP Ayam.",
        "Input tanggal DROP.",
        "Pilih supplier Nana / supplier ayam.",
        "Input kg ayam dan harga/kg aktual.",
        "Input bayar saat DROP jika ada, kalau belum bayar isi 0.",
        "Preview & Konfirmasi.",
        "Simpan live hanya jika data UAT sudah disetujui.",
        "Cek daftar DROP Ayam dan klik Detail.",
      ],
      passCriteria: [
        "DROP ID terbentuk.",
        "Lot Ayam terbentuk.",
        "Stok ayam/kg bertambah.",
        "Hutang Nana terbentuk jika belum lunas.",
        "Harga/kg terkunci sebagai harga aktual nota.",
        "Arsip Digital bisa menemukan DROP ID.",
      ],
    },
    {
      id: "UAT-02",
      title: "Produksi / Adukan → Potong Ayam → Stok Jadi",
      goal: "Menguji ayam lot dipakai produksi dan hasil jadi masuk stok.",
      steps: [
        "Buka Produksi / Adukan.",
        "Pilih lokasi produksi Tangerang atau Pemalang sesuai UAT.",
        "Pilih lot ayam aktif.",
        "Input total adukan.",
        "Cek preview: 1 adukan = 30 kg ayam = 1.000 pcs.",
        "Simpan live jika sudah disetujui.",
        "Cek Stok Ayam sisa berkurang.",
        "Cek Stok Jadi bertambah.",
      ],
      passCriteria: [
        "Chicken lot berkurang sesuai adukan.",
        "Stock movement OUT ayam terbentuk.",
        "Production batch terbentuk.",
        "Stock movement IN produk jadi terbentuk.",
        "Cost layer / modal produk jadi terbentuk.",
        "Stok Jadi ready bertambah.",
      ],
    },
    {
      id: "UAT-03",
      title: "Stok Jadi → Kasir / Order",
      goal: "Menguji stok jadi siap jual bisa dipakai order dan stok berkurang.",
      steps: [
        "Buka Stok Jadi dan catat stok ready awal.",
        "Buka Kasir / Order.",
        "Pilih customer UAT.",
        "Pilih produk Dimsum Ayam Mix dari Stok Bebas/Ready.",
        "Input qty kecil untuk UAT.",
        "Pastikan total tidak 0 kecuali mode promo/influencer valid.",
        "Simpan order sesuai mode penjualan.",
        "Cek stok ready setelah order.",
      ],
      passCriteria: [
        "Order tidak boleh kosong.",
        "Qty 0 ditolak.",
        "Order ID terbentuk.",
        "Order items terbaca.",
        "Stok jadi berkurang sesuai qty.",
        "Tidak ada order header Rp0/0 pcs yang tidak valid.",
        "Anti double-submit bekerja.",
      ],
    },
    {
      id: "UAT-04",
      title: "Order → Invoice → Payment / Piutang",
      goal: "Menguji order menjadi nota, pembayaran, dan piutang jika belum lunas.",
      steps: [
        "Dari order UAT, cek invoice/nota.",
        "Input pembayaran cash/transfer jika lunas.",
        "Atau sisakan sebagian sebagai piutang.",
        "Cek Payment ID.",
        "Cek Piutang jika belum lunas.",
        "Cek detail invoice, payment, piutang.",
      ],
      passCriteria: [
        "Invoice ID terbentuk.",
        "Payment ID terbentuk jika ada pembayaran.",
        "Piutang ID terbentuk jika belum lunas.",
        "Nominal invoice = item order.",
        "Payment masuk dompet yang benar.",
        "Piutang remaining benar.",
      ],
    },
    {
      id: "UAT-05",
      title: "Payment → Kas & Dompet → Mutasi",
      goal: "Menguji uang masuk customer menambah dompet dan bisa ditelusuri.",
      steps: [
        "Buka Kas & Dompet.",
        "Cari mutasi dari Payment ID.",
        "Klik sumber Payment/Invoice jika tersedia.",
        "Cek saldo dompet setelah pembayaran.",
        "Cek Papan Pantau: Uang Masuk Aktual berubah.",
      ],
      passCriteria: [
        "Wallet mutation IN terbentuk.",
        "Sumber mutasi menunjuk Payment/Invoice.",
        "Saldo dompet bertambah sesuai pembayaran.",
        "Papan Pantau membaca uang masuk aktual.",
      ],
    },
    {
      id: "UAT-06",
      title: "Hutang Nana → Bayar Hutang → Dompet OUT",
      goal: "Menguji pembayaran hutang supplier memotong dompet dan sisa hutang berubah.",
      steps: [
        "Buka Hutang Nana.",
        "Pilih hutang dari DROP UAT.",
        "Input pembayaran sebagian atau lunas sesuai UAT.",
        "Pilih dompet pembayaran.",
        "Simpan live jika disetujui.",
        "Cek Kas & Dompet untuk mutasi OUT.",
      ],
      passCriteria: [
        "Hutang payment ID terbentuk.",
        "Sisa hutang Nana berkurang.",
        "Wallet mutation OUT terbentuk.",
        "Sumber OUT menunjuk pembayaran hutang.",
        "Papan Pantau Sisa Hutang Nana berubah.",
      ],
    },
    {
      id: "UAT-07",
      title: "Kas Keluar / Belanja Operasional",
      goal: "Menguji belanja operasional memotong kas dan masuk arsip biaya.",
      steps: [
        "Buka Belanja & Kas Keluar.",
        "Input biaya kecil UAT atau gunakan data real yang disetujui.",
        "Pilih kategori dan dompet.",
        "Simpan jika sudah disetujui.",
        "Cek mutasi dompet OUT dan Arsip Digital.",
      ],
      passCriteria: [
        "Kas keluar ID terbentuk.",
        "Wallet mutation OUT terbentuk.",
        "Kategori biaya benar.",
        "Arsip bisa menemukan ID kas keluar.",
      ],
    },
    {
      id: "UAT-08",
      title: "4 Amplop Owner",
      goal: "Menguji uang masuk aktual bisa terbaca sebagai bahan alokasi owner.",
      steps: [
        "Buka 4 Amplop.",
        "Cek uang masuk aktual yang punya sumber jelas.",
        "Cek alokasi / belum dibagi.",
        "Klik detail amplop jika tersedia.",
        "Pastikan tidak memakai stok/PO sebagai uang.",
      ],
      passCriteria: [
        "4 Amplop hanya memakai uang masuk aktual.",
        "Alokasi punya sumber mutasi/dompet.",
        "Tidak mengambil nilai dari PO/stock/reserved.",
        "Detail amplop bisa ditelusuri.",
      ],
    },
    {
      id: "UAT-09",
      title: "Arsip Digital Drilldown",
      goal: "Menguji semua ID transaksi UAT bisa ditemukan dan rantainya nyambung.",
      steps: [
        "Buka Arsip Digital.",
        "Cari DROP ID.",
        "Cari Production Batch ID.",
        "Cari Order ID.",
        "Cari Invoice ID.",
        "Cari Payment ID.",
        "Cari Hutang/Payment Hutang ID.",
        "Cek related IDs dan timeline.",
      ],
      passCriteria: [
        "Semua ID bisa dicari.",
        "Related IDs muncul.",
        "Timeline masuk akal.",
        "Tidak ada angka yatim.",
      ],
    },
    {
      id: "UAT-10",
      title: "Papan Pantau Owner Setelah UAT",
      goal: "Menguji dashboard owner membaca perubahan operasional harian.",
      steps: [
        "Buka Papan Pantau.",
        "Klik Refresh Data.",
        "Cek Stok Ready, Sisa Ayam, Uang Masuk Aktual, Hutang Nana, Piutang, Payroll, 4 Amplop.",
        "Klik Radar Owner yang berubah.",
      ],
      passCriteria: [
        "Papan Pantau berubah mengikuti transaksi UAT.",
        "Radar Owner memberi arah tindakan yang benar.",
        "Benang Merah tidak putus.",
      ],
    },
  ],
  goNoGo: {
    goLiveBertahap: [
      "Semua UAT wajib PASS untuk DROP → Produksi → Stok → Order → Payment → Dompet → Arsip.",
      "Tidak ada transaksi Rp0/0 pcs yang tidak valid.",
      "Tidak ada stok minus.",
      "Tidak ada dompet berubah tanpa mutasi.",
      "Tidak ada payment tanpa invoice/source.",
      "Tidak ada hutang berubah tanpa payment/source.",
      "Arsip Digital bisa mencari ID utama.",
    ],
    holdGoLive: [
      "Order bisa double-submit.",
      "Stok berkurang tapi order item tidak terbaca.",
      "Payment masuk tapi dompet tidak berubah.",
      "Dompet berubah tanpa source ID.",
      "Produksi masuk tapi ayam tidak berkurang.",
      "Arsip ID tidak bisa ditemukan.",
    ],
  },
};

export function getOperationalDailyUatRows() {
  return operationalDailyUatPlan.phases.flatMap((phase) =>
    phase.steps.map((step, index) => ({
      phase: phase.id,
      title: phase.title,
      stepNo: index + 1,
      step,
      result: "",
      note: "",
    }))
  );
}
