import { useEffect, useMemo, useState } from "react";
import { approveSetoranCabang, createSetoranCabang, getSetoranCabangBootstrap, rejectSetoranCabang } from "../../lib/api/actions";
import { formatRupiah } from "../../lib/format/money";
import Badge from "../../components/ui/Badge";
import Button from "../../components/ui/Button";
import Card from "../../components/ui/Card";
import DataTable from "../../components/ui/DataTable";
import Modal from "../../components/ui/Modal";
import PageHeader from "../../components/ui/PageHeader";
import StatCard from "../../components/ui/StatCard";

const asArray = (v) => Array.isArray(v) ? v : [];
const num = (v) => { const n = Number(String(v ?? 0).replace(/[^0-9.-]/g, "")); return Number.isFinite(n) ? n : 0; };
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
const authRequired = (r) => String(r?.error?.code || r?.message || "").toUpperCase().includes("AUTH_REQUIRED");
const tone = (status) => { const v=String(status||"").toUpperCase(); if(v==="APPROVED") return "success"; if(v==="REJECTED") return "danger"; return "warning"; };
const wallet = (row={}) => ({ ...row, id: row.wallet_id || row.id || "", name: row.wallet_name || row.name || "Dompet", balance: num(row.current_balance ?? row.balance), location_code: row.location_code || "" });
const report = (row={}) => ({ ...row, report_id: row.report_id || row.id || "", expected_deposit: num(row.expected_deposit), approved_deposit_amount: num(row.approved_deposit_amount), pending_deposit_amount: num(row.pending_deposit_amount), period_label: row.date_start===row.date_end ? row.date_start : `${row.date_start} s/d ${row.date_end}` });
const deposit = (row={}) => ({ ...row, deposit_id: row.deposit_id || row.id || "", deposit_amount: num(row.deposit_amount), expected_amount: num(row.expected_amount), period_label: row.period_label || (row.date_start===row.date_end ? row.date_start : `${row.date_start} s/d ${row.date_end}`), items: asArray(row.items) });
function normalize(payload){ const d=payload?.data||payload||{}; return { health:d.health||{}, locations:asArray(d.locations), reports:asArray(d.eligible_reports||d.reports).map(report), deposits:asArray(d.deposits).map(deposit), sourceWallets:asArray(d.source_wallets).map(wallet), destinationWallets:asArray(d.destination_wallets||d.wallets).map(wallet), summary:{...(d.summary||{}), total_income:num(d.summary?.total_income), total_expense:num(d.summary?.total_expense), estimated_deposit:num(d.summary?.estimated_deposit), pending_amount:num(d.summary?.pending_amount), approved_amount:num(d.summary?.approved_amount), pending_count:num(d.summary?.pending_count), approved_count:num(d.summary?.approved_count)}, policy:d.policy||{} }; }

const DEPOSIT_COLUMNS=[
  {key:"deposit_date",label:"Tanggal"},
  {key:"deposit_id",label:"Setoran ID",render:(r)=><strong>{r.deposit_id}</strong>},
  {key:"location_code",label:"Cabang"},
  {key:"period_label",label:"Periode"},
  {key:"deposit_amount",label:"Nominal",render:(r)=>formatRupiah(r.deposit_amount)},
  {key:"destination_wallet_name",label:"Dompet Pusat"},
  {key:"status",label:"Status",render:(r)=><Badge tone={tone(r.status)}>{r.status}</Badge>},
];
const ITEM_COLUMNS=[
  {key:"date",label:"Tanggal"},{key:"module",label:"Sumber"},{key:"id",label:"ID"},{key:"description",label:"Keterangan"},{key:"amount",label:"Nominal",render:(r)=>formatRupiah(num(r.amount))},
];

export default function SetoranCabangPage({ session, onSessionExpired }){
  const current=today();
  const [filter,setFilter]=useState({report_mode:"daily",report_date:current,date_start:current,date_end:current,location_code:session?.user?.location_code||"TGR"});
  const [data,setData]=useState(()=>normalize({}));
  const [draft,setDraft]=useState({report_id:"",source_wallet_id:"",destination_wallet_id:"",deposit_date:current,deposit_amount:"0",payment_method:"TRANSFER",proof_reference:"",notes:""});
  const [selected,setSelected]=useState(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
  const token=session?.sessionToken||""; const role=String(session?.user?.role_id||"").toUpperCase(); const canApprove=role==="ROLE-OWNER"||role==="ROLE-HO-ADMIN";
  const request=useMemo(()=>({...filter,report_date:filter.report_mode==="period"?filter.date_start:filter.report_date,date_start:filter.report_mode==="period"?filter.date_start:filter.report_date,date_end:filter.report_mode==="period"?filter.date_end:filter.report_date}),[filter]);
  const selectedReport=data.reports.find((r)=>r.report_id===draft.report_id)||null; const source=data.sourceWallets.find((w)=>w.id===draft.source_wallet_id)||null; const destination=data.destinationWallets.find((w)=>w.id===draft.destination_wallet_id)||null;

  const load=async()=>{ setLoading(true);setError("");try{const result=await getSetoranCabangBootstrap(token,request);if(authRequired(result))return onSessionExpired?.();if(!result?.success)return setError(result?.message||"Gagal membaca setoran cabang.");const n=normalize(result.data||result);setData(n);setDraft((v)=>({...v,report_id:v.report_id||n.reports[0]?.report_id||"",source_wallet_id:v.source_wallet_id||n.sourceWallets[0]?.id||"",destination_wallet_id:v.destination_wallet_id||n.destinationWallets[0]?.id||"",deposit_amount:v.deposit_amount!=="0"?v.deposit_amount:String(n.reports[0]?.expected_deposit||n.summary.estimated_deposit||0)}));}catch(e){setError(e?.message||"Gagal membaca setoran cabang.");}finally{setLoading(false);}};
  useEffect(()=>{load();/* eslint-disable-next-line react-hooks/exhaustive-deps */},[]);

  const create=async()=>{setSaving(true);setError("");setSuccess("");try{if(!draft.report_id)return setError("Pilih laporan cabang yang sudah disubmit.");if(num(draft.deposit_amount)<=0)return setError("Nominal setoran wajib lebih dari 0.");const result=await createSetoranCabang(token,{...request,...draft,deposit_amount:num(draft.deposit_amount),expected_amount:selectedReport?.expected_deposit||0});if(authRequired(result))return onSessionExpired?.();if(!result?.success)return setError(result?.message||"Setoran gagal disimpan.");setSuccess(result?.message||"Setoran pending berhasil dibuat.");setDraft((v)=>({...v,deposit_amount:"0",proof_reference:"",notes:""}));await load();}catch(e){setError(e?.message||"Setoran gagal disimpan.");}finally{setSaving(false);}};
  const process=async(action)=>{if(!selected)return;setSaving(true);setError("");setSuccess("");try{const fn=action==="approve"?approveSetoranCabang:rejectSetoranCabang;const result=await fn(token,{deposit_id:selected.deposit_id,notes:action==="approve"?"Setoran diterima dan divalidasi Tangerang.":"Bukti/nominal perlu diperbaiki.",reason:action==="reject"?"Bukti/nominal perlu diperbaiki.":""});if(authRequired(result))return onSessionExpired?.();if(!result?.success)return setError(result?.message||"Setoran gagal diproses.");setSuccess(result?.message||"Setoran berhasil diproses.");setSelected(null);await load();}catch(e){setError(e?.message||"Setoran gagal diproses.");}finally{setSaving(false);}};

  return <div className="da-page-stack">
    <PageHeader title="Setoran Cabang" description="Setoran dibuat dari laporan yang sudah disubmit. Status pending tidak mengubah saldo; approval Tangerang memindahkan uang dari dompet cabang ke dompet pusat." badge="Validasi Setoran" />
    <Card><div className="da-card-header-row"><div><div className="da-section-kicker">Closing & Settlement</div><h2>Laporan → Setoran Pending → Validasi Tangerang</h2><p className="da-muted">Approval membuat pasangan mutasi OUT cabang dan IN pusat. Setoran bukan omzet baru.</p></div><div className="da-card-actions"><Badge tone={data.health?.ready?"success":"danger"}>{data.health?.ready?"Siap Validasi":"Gerbang Setoran Belum Siap"}</Badge><Button variant="ghost" onClick={load} disabled={loading}>{loading?"Menarik...":"Refresh Data"}</Button></div></div>
      <div className="da-detail-grid" style={{marginTop:16}}><label className="da-detail-box"><strong>Mode</strong><select value={filter.report_mode} onChange={(e)=>setFilter((v)=>({...v,report_mode:e.target.value}))}><option value="daily">Harian</option><option value="period">Periode</option></select></label>{filter.report_mode==="period"?<><label className="da-detail-box"><strong>Mulai</strong><input type="date" value={filter.date_start} onChange={(e)=>setFilter((v)=>({...v,date_start:e.target.value}))}/></label><label className="da-detail-box"><strong>Sampai</strong><input type="date" value={filter.date_end} onChange={(e)=>setFilter((v)=>({...v,date_end:e.target.value}))}/></label></>:<label className="da-detail-box"><strong>Tanggal</strong><input type="date" value={filter.report_date} onChange={(e)=>setFilter((v)=>({...v,report_date:e.target.value}))}/></label>}<label className="da-detail-box"><strong>Cabang</strong><select value={filter.location_code} onChange={(e)=>setFilter((v)=>({...v,location_code:e.target.value}))}>{data.locations.length===0?<option value={filter.location_code}>{filter.location_code}</option>:data.locations.map((l)=><option key={l.location_id} value={l.location_code}>{l.location_name} · {l.location_code}</option>)}</select></label></div>
      {error?<div className="da-form-warning">{error}</div>:null}{success?<div className="da-form-success">{success}</div>:null}
    </Card>
    <div className="da-grid da-grid-3"><StatCard label="Estimasi Setoran" value={formatRupiah(data.summary.estimated_deposit)} description="Dari laporan transaksi hidup."/><StatCard label="Pending Tangerang" value={formatRupiah(data.summary.pending_amount)} description={`${data.summary.pending_count} setoran menunggu validasi.`} tone="warning"/><StatCard label="Sudah Disahkan" value={formatRupiah(data.summary.approved_amount)} description={`${data.summary.approved_count} setoran sudah dipindahkan.`} tone="success"/></div>
    <Card><div className="da-card-header-row"><div><div className="da-section-kicker">Buat Setoran</div><h2>Kirim Setoran dari Laporan Cabang</h2><p className="da-muted">Pilih laporan, dompet asal cabang, dan dompet tujuan Tangerang.</p></div><Badge tone="warning">Pending dulu</Badge></div>
      <div className="da-detail-grid" style={{marginTop:16}}><label className="da-detail-box"><strong>Laporan</strong><select value={draft.report_id} onChange={(e)=>{const r=data.reports.find((x)=>x.report_id===e.target.value);setDraft((v)=>({...v,report_id:e.target.value,deposit_amount:String(r?.expected_deposit||0)}));}}><option value="">Pilih laporan</option>{data.reports.map((r)=><option key={r.report_id} value={r.report_id}>{r.report_id} · {r.period_label} · {r.status}</option>)}</select></label><label className="da-detail-box"><strong>Dompet Asal Cabang</strong><select value={draft.source_wallet_id} onChange={(e)=>setDraft((v)=>({...v,source_wallet_id:e.target.value}))}><option value="">Pilih dompet asal</option>{data.sourceWallets.map((w)=><option key={w.id} value={w.id}>{w.name} · saldo {formatRupiah(w.balance)}</option>)}</select></label><label className="da-detail-box"><strong>Dompet Tujuan Pusat</strong><select value={draft.destination_wallet_id} onChange={(e)=>setDraft((v)=>({...v,destination_wallet_id:e.target.value}))}><option value="">Pilih dompet pusat</option>{data.destinationWallets.map((w)=><option key={w.id} value={w.id}>{w.name} · {w.location_code}</option>)}</select></label><label className="da-detail-box"><strong>Nominal</strong><input type="number" value={draft.deposit_amount} onChange={(e)=>setDraft((v)=>({...v,deposit_amount:e.target.value}))}/><p>Estimasi laporan: {formatRupiah(selectedReport?.expected_deposit||0)}</p></label><label className="da-detail-box"><strong>Tanggal Setoran</strong><input type="date" value={draft.deposit_date} onChange={(e)=>setDraft((v)=>({...v,deposit_date:e.target.value}))}/></label><label className="da-detail-box"><strong>Referensi Bukti</strong><input value={draft.proof_reference} onChange={(e)=>setDraft((v)=>({...v,proof_reference:e.target.value}))} placeholder="Nomor transfer / nama file bukti"/></label></div>
      <label className="da-detail-box" style={{display:"block",marginTop:14}}><strong>Catatan / Selisih</strong><input value={draft.notes} onChange={(e)=>setDraft((v)=>({...v,notes:e.target.value}))} placeholder="Wajib jika nominal berbeda dari estimasi"/></label>
      <div className="da-form-warning" style={{marginTop:14}}>Sebelum disahkan: saldo cabang dan pusat belum berubah. Setelah disahkan: {source?.name||"dompet cabang"} OUT dan {destination?.name||"dompet pusat"} IN dalam satu transaksi.</div><div className="da-form-actions"><Button variant="primary" onClick={create} disabled={saving||!data.health?.ready}>{saving?"Menyimpan...":"Kirim Setoran Pending"}</Button></div>
    </Card>
    <Card><div className="da-card-header-row"><div><div className="da-section-kicker">Antrean Validasi</div><h2>Setoran Cabang yang Tercatat</h2><p className="da-muted">Klik baris untuk detail dan tindakan owner/Tangerang.</p></div><Badge tone="success">Data Aktual</Badge></div><DataTable columns={DEPOSIT_COLUMNS} rows={data.deposits} getRowKey={(r)=>r.deposit_id} onRowClick={setSelected}/></Card>
    <Modal open={Boolean(selected)} title="Detail Setoran Cabang" subtitle={selected?.deposit_id||""} onClose={()=>setSelected(null)}><div className="da-detail-grid" style={{marginBottom:16}}><div className="da-detail-box"><strong>Nominal</strong><p>{formatRupiah(selected?.deposit_amount||0)}</p></div><div className="da-detail-box"><strong>Dompet Asal</strong><p>{selected?.source_wallet_name}</p></div><div className="da-detail-box"><strong>Dompet Pusat</strong><p>{selected?.destination_wallet_name}</p></div><div className="da-detail-box"><strong>Status</strong><p><Badge tone={tone(selected?.status)}>{selected?.status}</Badge></p></div><div className="da-detail-box"><strong>Mutasi OUT</strong><p>{selected?.out_mutation_id||"Belum ada"}</p></div><div className="da-detail-box"><strong>Mutasi IN</strong><p>{selected?.in_mutation_id||"Belum ada"}</p></div></div><DataTable columns={ITEM_COLUMNS} rows={selected?.items||[]} getRowKey={(r,i)=>`${r.id}-${i}`}/>{canApprove&&String(selected?.status).toUpperCase()==="PENDING_OWNER"?<div className="da-form-actions"><Button variant="ghost" onClick={()=>process("reject")} disabled={saving}>Tolak / Revisi</Button><Button variant="primary" onClick={()=>process("approve")} disabled={saving}>Sahkan Setoran</Button></div>:null}</Modal>
  </div>;
}
